import type { Metadata } from "next";
import "./globals.css";
import { WalletContextProvider } from "@/providers/WalletProvider";
import GoogleProvider from "@/providers/GoogleProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GoogleProvider>
          <WalletContextProvider>{children}</WalletContextProvider>
        </GoogleProvider>
      </body>
    </html>
  );
}
